logging:
  level:
    org.springframework.web: ERROR
    com:
      ticketapi:
        TicketManagementApp: DEBUG
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %5level %logger{36} - %msg%n'
  file:
    name: 'C:\Users\Ankit anshu\Downloads\TicketManagementApp\TicketManagementApp\src\main\resources\api.log'